FROM node:20 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . . 
RUN npm run build

FROM node:20 AS production

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules

ENV VITE_FILE_BASE_URL=http://localhost:8888/ \
    VITE_BACKEND_SERVER=http://your_backend_url_server.com/ \
    PROD=false

RUN npm install -g vite

EXPOSE 4173

CMD ["vite", "preview", "--port", "4173", "--host"]
