FROM node:20-alpine AS builder

WORKDIR /tmp

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npm run build


FROM node:20-alpine

WORKDIR /app

COPY --from=builder /tmp/dist ./dist
COPY --from=builder /tmp/package.json ./
COPY --from=builder /tmp/node_modules ./node_modules

ENV PORT=5000 \
    MONGO_URI=mongodb://localhost:27017/

EXPOSE 5000

CMD ["node", "dist/main"]
