name: Monorepo CI/CD

on:
  pull_request:
    branches: [master]
  push:
    branches: [feature/nest_advanced]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      nest_changed: ${{ steps.filter.outputs.nest_advanced }}
      nextjs_changed: ${{ steps.filter.outputs.nextjs_crud_app }}
      express_changed: ${{ steps.filter.outputs.express_server }}
      frontend_changed: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            nest_advanced:
              - 'nest_advanced/**'
            nextjs_crud_app:
              - 'nextjs_crud_app/**'
            express_server:
              - 'express_server/**'
            frontend:
              - 'frontend/**'

  ## === NESTJS === ##
  lint-test-nest:
    needs: detect-changes
    if: needs.detect-changes.outputs.nest_changed == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nest_advanced
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint
      - run: npm run test

  build-push-nest:
    needs: lint-test-nest
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/feature/nest_advanced'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: ./nest_advanced
          push: true
          tags: |
            lalitrajak312/nest-advanced:latest
            lalitrajak312/nest-advanced:${{ github.sha }}

   ## === NEXT.JS CRUD APP === ##
  build-push-nextjs:
    needs: lint-test-nextjs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/feature/nest_advanced'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.13.1
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: ./nextjs_crud_app
          push: true
          tags: |
            lalitrajak312/nextjs-crud:latest
            lalitrajak312/nextjs-crud:${{ github.sha }}
          build-args: |
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}

  ## === EXPRESS SERVER === ##
  build-push-express:
    needs: detect-changes
    if: needs.detect-changes.outputs.express_changed == 'true' && github.ref == 'refs/heads/feature/nest_advanced'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: ./express_server
          push: true
          tags: |
            lalitrajak312/express-server:latest
            lalitrajak312/express-server:${{ github.sha }}
          build-args: |
            MONGODB_URI=${{ secrets.MONGODB_URI }}

  ## === FRONTEND === ##
  build-push-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend_changed == 'true' && github.ref == 'refs/heads/feature/nest_advanced'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            lalitrajak312/frontend:latest
            lalitrajak312/frontend:${{ github.sha }}
          build-args: |
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
